---
kind: pipeline
name: deploy-kubernetes-dev
type: kubernetes

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    - main
  event:
    - push
    - merge

steps:
  - name: deploy-dev
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/kd
    environment:
      # Application settings
      AWS_ACCESS_KEY_ID:
        from_secret: DEV_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: DEV_AWS_SECRET_ACCESS_KEY
      METADATA_SOURCE_HOST:
        from_secret: DEV_METADATA_SOURCE_HOST
      METADATA_SOURCE_DATABASE:
        from_secret: DEV_METADATA_SOURCE_DATABASE
      METADATA_SOURCE_PORT:
        from_secret: DEV_METADATA_SOURCE_PORT
      METADATA_SOURCE_USER:
        from_secret: DEV_METADATA_SOURCE_USER
      METADATA_SOURCE_PASSWORD:
        from_secret: DEV_METADATA_SOURCE_PASSWORD
      METADATA_SOURCE_SCHEMA:
        from_secret: DEV_METADATA_SOURCE_SCHEMA
      METADATA_SOURCE_TABLE:
        from_secret: DEV_METADATA_SOURCE_TABLE
      METADATA_FETCH_SIZE: 100
      METADATA_CHUNK_SIZE: 100
      S3_SOURCE_BUCKET:
        from_secret: DEV_S3_SOURCE_BUCKET
      S3_TARGET_BUCKET:
        from_secret: DEV_S3_TARGET_BUCKET
      S3_ENDPOINT_URL: https://s3.eu-west-2.amazonaws.com
      KAFKA_BOOTSTRAP_SERVERS:
        from_secret: DEV_KAFKA_BOOTSTRAP_SERVERS
      KAFKA_INGEST_TOPIC: txa-decs-ingest
      KAFKA_DELETE_TOPIC: txa-decs-delete
      SLACK_DECS_URL:
        from_secret: DEV_SLACK_DECS_URL
      SLACK_TXA_URL:
        from_secret: DEV_SLACK_TXA_URL
      # Kubernetes deployment target
      KUBE_TOKEN:
        from_secret: DEV_KUBE_TOKEN
      KUBE_NAMESPACE: dsa-textanalytics-dev
      KUBE_CLUSTER: acp-notprod
    commands:
      - apk add -U curl  # to get acp kubernetes certificate
      - /bin/bash kube/deploy.sh

---
kind: pipeline
name: deploy-kubernetes
type: kubernetes

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - promote
  target:
    - mode
    - prod

steps:
  - name: deploy-mode
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/kd
    environment:
      # Application settings
      AWS_ACCESS_KEY_ID:
        from_secret: MODE_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: MODE_AWS_SECRET_ACCESS_KEY
      METADATA_SOURCE_HOST:
        from_secret: MODE_METADATA_SOURCE_HOST
      METADATA_SOURCE_DATABASE:
        from_secret: MODE_METADATA_SOURCE_DATABASE
      METADATA_SOURCE_PORT:
        from_secret: MODE_METADATA_SOURCE_PORT
      METADATA_SOURCE_USER:
        from_secret: MODE_METADATA_SOURCE_USER
      METADATA_SOURCE_PASSWORD:
        from_secret: MODE_METADATA_SOURCE_PASSWORD
      METADATA_SOURCE_SCHEMA:
        from_secret: MODE_METADATA_SOURCE_SCHEMA
      METADATA_SOURCE_TABLE:
        from_secret: MODE_METADATA_SOURCE_TABLE
      METADATA_FETCH_SIZE: 100
      METADATA_CHUNK_SIZE: 100
      S3_SOURCE_BUCKET:
        from_secret: MODE_S3_SOURCE_BUCKET
      S3_TARGET_BUCKET:
        from_secret: MODE_S3_TARGET_BUCKET
      S3_ENDPOINT_URL: https://s3.eu-west-2.amazonaws.com
      KAFKA_BOOTSTRAP_SERVERS:
        from_secret: MODE_KAFKA_BOOTSTRAP_SERVERS
      KAFKA_INGEST_TOPIC: txa-decs-ingest
      KAFKA_DELETE_TOPIC: txa-decs-delete
      SLACK_DECS_URL:
        from_secret: MODE_SLACK_DECS_URL
      SLACK_TXA_URL:
        from_secret: MODE_SLACK_TXA_URL
      # Kubernetes deployment target
      KUBE_TOKEN:
        from_secret: MODE_KUBE_TOKEN
      KUBE_NAMESPACE: dsa-textanalytics-mode
      KUBE_CLUSTER: acp-prod
    commands:
      - apk add -U curl  # to get acp kubernetes certificate
      - /bin/bash kube/deploy.sh
    when:
      event:
        - promote
      target:
        - mode

  - name: deploy-prod
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/kd
    environment:
      # Application settings
      AWS_ACCESS_KEY_ID:
        from_secret: PROD_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: PROD_AWS_SECRET_ACCESS_KEY
      METADATA_SOURCE_HOST:
        from_secret: PROD_METADATA_SOURCE_HOST
      METADATA_SOURCE_DATABASE:
        from_secret: PROD_METADATA_SOURCE_DATABASE
      METADATA_SOURCE_PORT:
        from_secret: PROD_METADATA_SOURCE_PORT
      METADATA_SOURCE_USER:
        from_secret: PROD_METADATA_SOURCE_USER
      METADATA_SOURCE_PASSWORD:
        from_secret: PROD_METADATA_SOURCE_PASSWORD
      METADATA_SOURCE_SCHEMA:
        from_secret: PROD_METADATA_SOURCE_SCHEMA
      METADATA_SOURCE_TABLE:
        from_secret: PROD_METADATA_SOURCE_TABLE
      METADATA_FETCH_SIZE: 100
      METADATA_CHUNK_SIZE: 100
      S3_SOURCE_BUCKET:
        from_secret: PROD_S3_SOURCE_BUCKET
      S3_TARGET_BUCKET:
        from_secret: PROD_S3_TARGET_BUCKET
      S3_ENDPOINT_URL: https://s3.eu-west-2.amazonaws.com
      KAFKA_BOOTSTRAP_SERVERS:
        from_secret: PROD_KAFKA_BOOTSTRAP_SERVERS
      KAFKA_INGEST_TOPIC: txa-decs-ingest
      KAFKA_DELETE_TOPIC: txa-decs-delete
      SLACK_DECS_URL:
        from_secret: PROD_SLACK_DECS_URL
      SLACK_TXA_URL:
        from_secret: PROD_SLACK_TXA_URL
      # Kubernetes deployment target
      KUBE_TOKEN:
        from_secret: PROD_KUBE_TOKEN
      KUBE_NAMESPACE: dsa-textanalytics-prod
      KUBE_CLUSTER: acp-prod
    commands:
      - apk add -U curl  # to get acp kubernetes certificate
      - /bin/bash kube/deploy.sh
    when:
      event:
        - promote
      target:
        - prod

...
