---
version: '1'  # Local stack for testing txa-decs-interface
services:

  postgres:
    hostname: postgres
    container_name: postgres
    build:
      dockerfile: postgres.Dockerfile
      context: .
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  localstack:
    image: localstack/localstack:1.4.0
    restart: on-failure
    ports:
      - "4566:4566"
    networks:
      hocs-network:
        aliases:
          - localhost.localstack.cloud
    environment:
      HOSTNAME_EXTERNAL: localstack
      SERVICES: sqs,sns,s3
      LOCALSTACK_HOSTNAME: "localhost.localstack.cloud"
      SQS_PROVIDER: "elasticmq"
      AWS_ACCESS_KEY_ID: UNSET
      AWS_SECRET_ACCESS_KEY: UNSET
      AWS_DEFAULT_REGION: eu-west-2
    healthcheck:
      test: "bash -c 'AWS_ACCESS_KEY_ID=fake AWS_SECRET_ACCESS_KEY=fake awslocal s3 ls'"
      timeout: 5s
      retries: 40
    volumes:
      - ${PWD}/ci/localstack/0-install-dependencies.sh:/etc/localstack/init/ready.d/0-install-dependencies.sh
      - ${PWD}/ci/localstack/1-setup-buckets.sh:/etc/localstack/init/ready.d/1-setup-buckets.sh
      - ${PWD}/src/test/resources/s3_data:/tmp/src/test/resources/s3_data
      - ${PWD}/src/test/resources/upload_mock_s3_objects.sh:/etc/localstack/init/ready.d/upload_mock_s3_objects.sh

networks:
  hocs-network: