apiVersion: v1
kind: Secret
type: opaque
metadata:
  name: txa-secrets
data:
  METADATA_SOURCE_USER: {{ .METADATA_SOURCE_USER | b64enc }}
  METADATA_SOURCE_PASSWORD: {{ .METADATA_SOURCE_PASSWORD | b64enc }}
  SLACK_DECS_URL: {{ .SLACK_DECS_URL | b64enc }}
  SLACK_TXA_URL: {{ .SLACK_TXA_URL | b64enc }}
