info:
  app_name: hocs-txa-document-extractor
  environment: default

document-metadata:
  driver: org.postgresql.Driver
  ServerName: ${METADATA_SOURCE_HOST:localhost}
  DatabaseName: ${METADATA_SOURCE_DATABASE:postgres}
  PortNumber: ${METADATA_SOURCE_PORT:5432}
  User: ${METADATA_SOURCE_USER:postgres}
  Password: ${METADATA_SOURCE_PASSWORD:admin}
  metadata_schema: ${METADATA_SOURCE_SCHEMA:metadata}
  metadata_table: ${METADATA_SOURCE_TABLE:document_metadata}
  # fetch_size determines how many records are fetched from the database
  fetch_size: ${METADATA_FETCH_SIZE:2}
  # chunk_size determines how many records are read/processed before writing
  chunk_size: ${METADATA_CHUNK_SIZE:2}
  # Timestamps are expected as strings in format "YYYY-MM-DD HH:mm:SS"
  last_ingest: ${METADATA_LAST_INGEST:}
  last_delete: ${METADATA_LAST_DELETE:}

s3:
  source_bucket: ${S3_SOURCE_BUCKET:trusted-bucket}
  target_bucket: ${S3_TARGET_BUCKET:untrusted-bucket}
  endpoint_url: ${S3_ENDPOINT_URL:http://s3.localhost.localstack.cloud:4566}

kafka:
  bootstrap_servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  ingest_topic: ${KAFKA_INGEST_TOPIC:decs-ingest}
  delete_topic: ${KAFKA_DELETE_TOPIC:decs-delete}

slack:
  decs_channel: ${DECS_SLACK_URL:}
  txa_channel: ${TXA_SLACK_URL:}

spring-batch-db:
  datasource:
    jdbc-url: jdbc:h2:mem:jobstate
    driver-class-name: org.h2.Driver
